### ISSUE TITLE
Server doesn't load

### ISSUE THREAD

**Issue by evitiello** [henrytriplette/penplotter-webserver#4]
Hi!
After running the install on a RPI400, which seemed to go fine (the device rebooted by itself), I'm unable to connect to the website - it just doesn't respond on port 5000.  Is there any way to debug this?  Does it generate logs anywhere (I was unable to find any)?

**Comment by evitiello** [comment]
ok, I tracked down the error "The Werkzeug web server is not designed to run in production".

Based on: https://github.com/projecthorus/radiosonde_auto_rx/issues/654

It looks like it's because it's running under systemd, and doesn't have a tty available.

changing line 298 in main.py to the following fixed it:

`socketio.run(app, host='0.0.0.0', port=5000, debug=True, allow_unsafe_werkzeug=True)`

**Comment by evitiello** [comment]
Submitted Pull Request https://github.com/henrytriplette/penplotter-webserver/pull/5

**Comment by henrytriplette** [comment]
HI Eric! Sorry for the late response.

Thanks for the fix, I'll merge it asap!

**Comment by evitiello** [comment]
Awesome, thanks!
